In [1]:
import numpy as np

# Boolean Indexing

In [2]:
arr = np.array([10,15,20,25,30])

In [3]:
arr[[True,False,True,False,True]]

array([10, 20, 30])

In [4]:
l = [True,False,True,True,False]
l

[True, False, True, True, False]

In [5]:
arr[l]

array([10, 20, 25])

In [6]:
arr

array([10, 15, 20, 25, 30])

In [7]:
l2 = (arr%2==0)
l2

array([ True, False,  True, False,  True])

In [8]:
arr[l2]

array([10, 20, 30])

In [9]:
arr[arr%2==0]

array([10, 20, 30])

In [10]:
age = np.array([42,18,22,13,16])

In [11]:
age

array([42, 18, 22, 13, 16])

In [12]:
age[age > 18]

array([42, 22])

In [13]:
age[age == 22]

array([22])

In [14]:
a2 = np.array([[3,5,7],[1,2,9],[6,4,2]])
a2

array([[3, 5, 7],
       [1, 2, 9],
       [6, 4, 2]])

In [15]:
l1 =[True,False,True]

In [17]:
a2[l1]

array([[3, 5, 7],
       [6, 4, 2]])

# Boolean Mask (Masking Array)

In [18]:
arr

array([10, 15, 20, 25, 30])

In [19]:
l

[True, False, True, True, False]

In [21]:
print(np.ma.array(arr,mask=l))

[-- 15 -- -- 30]


In [22]:
Odd = np.ma.array(arr,mask = arr % 2 == 0)
print(Odd)

[-- 15 -- 25 --]


In [23]:
a2

array([[3, 5, 7],
       [1, 2, 9],
       [6, 4, 2]])

In [25]:
a2.flatten()

array([3, 5, 7, 1, 2, 9, 6, 4, 2])

### To converts Multi-Dimensional array into 1D array

In [26]:
a2.reshape(-1)

array([3, 5, 7, 1, 2, 9, 6, 4, 2])

### Converts Multi-Dimensional array into 1D array

In [27]:
a2.ravel()

array([3, 5, 7, 1, 2, 9, 6, 4, 2])

In [29]:
a1d = np.arange(12)
a1d

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [30]:
a1d.reshape(4,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [31]:
a1d.reshape(2,-1)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [32]:
a1d.reshape(-1,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [33]:
a1d.reshape(-1,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [34]:
a1d.reshape(2,3,2)

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]]])

## Brodcasting of Array

#### Brodcasting is a powerful mechanism in numpy that allows Array Operations between arrays of different shapes without  copying data.

##### There are four types of array:
###### 1. Scalar
###### 2. Vector
###### 3. Matrix

In [35]:
arr

array([10, 15, 20, 25, 30])

#### 1) Scalar

In [36]:
s1 = [3]
s2 = 5
s3 = np.array([6])

In [37]:
arr + s2

array([15, 20, 25, 30, 35])

In [38]:
arr + s1

array([13, 18, 23, 28, 33])

In [39]:
arr + 9

array([19, 24, 29, 34, 39])

In [40]:
arr + s3

array([16, 21, 26, 31, 36])

#### 2) Vector Brodcasting

##### (a) Row vector brodcasting(1D)

In [42]:
a1 = np.array([[1,2,3],
               [4,5,6]])
a2 = np.array([10,20,30])

print(a1 + a2)

[[11 22 33]
 [14 25 36]]


##### (b) Column vector brodcasting

In [44]:
a1 = np.array([[1,2,3],
               [4,5,6]])
a2 = np.array([10,20]).reshape(-1,1)

print(a1 + a2)

[[11 12 13]
 [24 25 26]]


#### 3) Matrix Brodcasting

In [48]:
a1 = np.array([[1],[2]])
a2 = np.array([[10,20,30]])

print(a1)
print()
print(a2)
print()

a3 = a1 + a2 
print(a3)

[[1]
 [2]]

[[10 20 30]]

[[11 21 31]
 [12 22 32]]


In [50]:
a1 = np.array([[1,2],[3,4]])
a2 = np.array([1,2,3])

print(a1)
print()
print(a2)

a3 = a1 + a2
print(a3)

[[1 2]
 [3 4]]

[1 2 3]


ValueError: operands could not be broadcast together with shapes (2,2) (3,) 