In [2]:
import numpy as np

# Mathematical Operations

In [3]:
a1 = np.array([1,8,6,7,9])
a1

array([1, 8, 6, 7, 9])

In [4]:
a2 = np.array([2,8,7,6,3])
a2

array([2, 8, 7, 6, 3])

In [4]:
a1 + a2 

array([ 3, 16, 13, 13, 12])

In [5]:
a1 - a2

array([-1,  0, -1,  1,  6])

In [6]:
a1 * a2

array([ 2, 64, 42, 42, 27])

In [7]:
a1/a2

array([0.5       , 1.        , 0.85714286, 1.16666667, 3.        ])

In [9]:
ans = a1 ** a2
ans

array([       1, 16777216,   279936,   117649,      729])

In [10]:
np.sqrt(ans)

array([1.00000000e+00, 4.09600000e+03, 5.29089784e+02, 3.43000000e+02,
       2.70000000e+01])

In [11]:
a3 = np.array([1.2,2.5,3.7,4.9])
a3

array([1.2, 2.5, 3.7, 4.9])

In [12]:
np.floor(a3)

array([1., 2., 3., 4.])

In [13]:
np.ceil(a3)

array([2., 3., 4., 5.])

In [14]:
np.round(a3)

array([1., 2., 4., 5.])

# Combining Arrays

In [5]:
a1

array([1, 8, 6, 7, 9])

In [6]:
a2

array([2, 8, 7, 6, 3])

### To combines 1D Arrays.

In [7]:
np.concatenate((a1,a2))

array([1, 8, 6, 7, 9, 2, 8, 7, 6, 3])

In [8]:
arr1 = np.array([[3,5,7],[1,2,9],[4,6,8]])
arr2 = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [9]:
print(arr1)

[[3 5 7]
 [1 2 9]
 [4 6 8]]


In [10]:
print(arr2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


### To combine vertically

In [11]:
np.vstack((arr1,arr2))

array([[3, 5, 7],
       [1, 2, 9],
       [4, 6, 8],
       [1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### To combine Horizontally

In [12]:
np.hstack((arr1,arr2))

array([[3, 5, 7, 1, 2, 3],
       [1, 2, 9, 4, 5, 6],
       [4, 6, 8, 7, 8, 9]])

### To convert any matrix into 1d Array.

In [13]:
arr1.flatten()

array([3, 5, 7, 1, 2, 9, 4, 6, 8])

In [14]:
arr = np.array([1,2,3,4,5,6])
arr

array([1, 2, 3, 4, 5, 6])

In [15]:
np.split(arr,3)

[array([1, 2]), array([3, 4]), array([5, 6])]

In [16]:
arr2 = np.array([[1,2,3,4,5,6],
                 [7,8,9,10,11,12]])
arr2

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

### To split horizontally

In [17]:
np.hsplit(arr2,3)

[array([[1, 2],
        [7, 8]]),
 array([[ 3,  4],
        [ 9, 10]]),
 array([[ 5,  6],
        [11, 12]])]

### To split verrtically

In [21]:
np.vsplit(arr2,2)

[array([[1, 2, 3, 4, 5, 6]]), array([[ 7,  8,  9, 10, 11, 12]])]

# Searching in Array.

In [22]:
a1

array([1, 8, 6, 7, 9])

In [23]:
np.where(a1 == 7)

(array([3]),)

In [25]:
a3 = np.array([1,3,5,6,3,7,1])
a3

array([1, 3, 5, 6, 3, 7, 1])

In [26]:
np.where(a3 == 3)

(array([1, 4]),)

In [27]:
np.where(a3 > 3)

(array([2, 3, 5]),)

In [28]:
arr1

array([[3, 5, 7],
       [1, 2, 9],
       [4, 6, 8]])

In [29]:
np.where(arr1 == 5)

(array([0]), array([1]))

In [30]:
arr3 = np.array([[1,2,3],[2,5,7],[4,5,2]])
arr3

array([[1, 2, 3],
       [2, 5, 7],
       [4, 5, 2]])

In [31]:
np.where(arr3 == 2)

(array([0, 1, 2]), array([1, 0, 2]))

### Sorting of Array

In [32]:
a1

array([1, 8, 6, 7, 9])

In [33]:
np.sort(a1)

array([1, 6, 7, 8, 9])

In [ ]:
## Find how to sort in Decending Order

In [34]:
arr3 

array([[1, 2, 3],
       [2, 5, 7],
       [4, 5, 2]])

In [35]:
np.sort(arr3)

array([[1, 2, 3],
       [2, 5, 7],
       [2, 4, 5]])

In [36]:
## Find how to sort in decending order 
## Find how to sort col-wise & row-wise

# Aggregating & Statistical Functions

In [37]:
a1

array([1, 8, 6, 7, 9])

In [38]:
np.sum(a1)

np.int64(31)

In [39]:
np.mean(a1)

np.float64(6.2)

In [40]:
np.median(a1)

np.float64(7.0)

In [41]:
np.max(a1)

np.int64(9)

In [42]:
np.min(a1)

np.int64(1)

In [43]:
np.std(a1)

np.float64(2.7856776554368237)

In [44]:
np.var(a1)

np.float64(7.76)

In [45]:
arr4 = np.array([[1,2,3],[4,5,6]])
arr4

array([[1, 2, 3],
       [4, 5, 6]])

In [46]:
np.sum(arr4)

np.int64(21)

In [47]:
np.sum(arr4,axis=1)

array([ 6, 15])

In [48]:
np.sum(arr4,axis=0)

array([5, 7, 9])