In [1]:
import numpy as np

In [2]:
dir(np)

['False_',
 'ScalarType',
 'True_',
 '_CopyMode',
 '_NoValue',
 '__NUMPY_SETUP__',
 '__all__',
 '__array_api_version__',
 '__array_namespace_info__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__dir__',
 '__doc__',
 '__expired_attributes__',
 '__file__',
 '__former_attrs__',
 '__future_scalars__',
 '__getattr__',
 '__loader__',
 '__name__',
 '__numpy_submodules__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_array_api_info',
 '_core',
 '_distributor_init',
 '_expired_attrs_2_0',
 '_globals',
 '_int_extended_msg',
 '_mat',
 '_msg',
 '_pyinstaller_hooks_dir',
 '_pytesttester',
 '_specific_msg',
 '_type_info',
 '_typing',
 '_utils',
 'abs',
 'absolute',
 'acos',
 'acosh',
 'add',
 'all',
 'allclose',
 'amax',
 'amin',
 'angle',
 'any',
 'append',
 'apply_along_axis',
 'apply_over_axes',
 'arange',
 'arccos',
 'arccosh',
 'arcsin',
 'arcsinh',
 'arctan',
 'arctan2',
 'arctanh',
 'argmax',
 'argmin',
 'argpartition',
 'argsort',
 'argwhere',
 'around',
 'array',
 'arr

## Creating an Array

In [3]:
l = [1, 4, 6, 8]

print(l)

[1, 4, 6, 8]


In [4]:
arr = np.array(l)
print(arr)

[1 4 6 8]


In [5]:
a2 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
a2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
a = np.zeros(5)
a

array([0., 0., 0., 0., 0.])

In [7]:
a3 = np.ones(5)
a3

array([1., 1., 1., 1., 1.])

In [8]:
a4 = np.eye(3)
a4

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [9]:
ar1 = np.zeros((4, 3))
ar1

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [10]:
ar2 = np.ones((3, 3))
ar2

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [11]:
ar3 = np.arange(10)
ar3

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
ar4 = np.arange(1, 11)
ar4

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [13]:
ar5 = np.arange(1, 11, 2)
ar5

array([1, 3, 5, 7, 9])

In [14]:
ar6 = np.linspace(1, 10, 5)
ar6

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [15]:
arr7 = np.full(5, 3)
arr7

array([3, 3, 3, 3, 3])

In [16]:
arr8 = np.full((3, 3), 9)
arr8

array([[9, 9, 9],
       [9, 9, 9],
       [9, 9, 9]])

In [17]:
r1 = np.random.rand(3, 3)
r1

array([[0.70960937, 0.06990722, 0.95766208],
       [0.25981533, 0.76740838, 0.90698671],
       [0.01062672, 0.81386796, 0.09916904]])

In [ ]:
r2 = np.random.rand(5)
r2

In [ ]:
r3 = np.random.randint(5)
r3

In [ ]:
r4 = np.random.randint(3, 10)
r4

In [ ]:
r5 = np.random.randint(3, 10, 5)
r5

In [ ]:
r6 = np.random.randint(3, 10, (3, 3))
r6

## Indexing of Array

In [4]:
a = np.arange(1, 10)

In [5]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
print(a[0])

In [ ]:
print(a[3])

In [ ]:
print(a[-1])

In [ ]:
print(a[-3])

In [ ]:
a2 = np.random.randint(1, 10, (3, 3))
a2

In [ ]:
print(a2[0][1])

In [ ]:
print(a2[2][0])

In [ ]:
print(a2[0, 1])

In [ ]:
print(a2[1, 2])

In [ ]:
print(a2)

## Slicing on Array

In [ ]:
a = np.arange(3, 10)
a

In [ ]:
a[0:3]

In [ ]:
a[-1:-5:-1]

In [ ]:
a[2:6]

In [ ]:
a

In [ ]:
a[0:]

In [ ]:
a[0::1]

In [ ]:
a[0::2]

In [ ]:
a[::]

In [ ]:
a[::-1]

In [ ]:
a2 = np.random.randint(1, 10, (3, 3))
print(a2)

In [ ]:
a2[0:2, 2]

In [ ]:
a2[0:, 1]

In [ ]:
a2[1, 0:2]

In [ ]:
a2

In [ ]:
a2[:, :]

In [ ]:
a2[0:, 1:]

## Shape, Size, and Datatype of Array

In [67]:
a

array([3, 4, 5, 6, 7, 8, 9])

In [68]:
print(a.shape)

(7,)


In [69]:
a2

array([[3, 2, 6],
       [5, 3, 3],
       [3, 4, 9]], dtype=int32)

In [70]:
print(a2.shape)

(3, 3)


In [71]:
print(a.size)

7


In [72]:
print(a2.size)

9


In [73]:
print(a.dtype)

int64


In [74]:
print(a2.dtype)

int32


## Mathematical Operations on Array

In [18]:
a1 = np.arange(11, 20)
a2 = np.arange(5, 14)

In [19]:
a1

array([11, 12, 13, 14, 15, 16, 17, 18, 19])

In [77]:
a2

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13])

In [78]:
a1 + a2

array([16, 18, 20, 22, 24, 26, 28, 30, 32])

In [79]:
a1 * a2

array([ 55,  72,  91, 112, 135, 160, 187, 216, 247])

In [80]:
a3 = np.array([16, 81, 25, 121, 9])

np.sqrt(a3)

array([ 4.,  9.,  5., 11.,  3.])