In [1]:
import numpy as np

In [3]:
dir(np)

['False_',
 'ScalarType',
 'True_',
 '_CopyMode',
 '_NoValue',
 '__NUMPY_SETUP__',
 '__all__',
 '__array_api_version__',
 '__array_namespace_info__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__dir__',
 '__doc__',
 '__expired_attributes__',
 '__file__',
 '__former_attrs__',
 '__future_scalars__',
 '__getattr__',
 '__loader__',
 '__name__',
 '__numpy_submodules__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_array_api_info',
 '_core',
 '_distributor_init',
 '_expired_attrs_2_0',
 '_globals',
 '_int_extended_msg',
 '_mat',
 '_msg',
 '_pyinstaller_hooks_dir',
 '_pytesttester',
 '_specific_msg',
 '_type_info',
 '_typing',
 '_utils',
 'abs',
 'absolute',
 'acos',
 'acosh',
 'add',
 'all',
 'allclose',
 'amax',
 'amin',
 'angle',
 'any',
 'append',
 'apply_along_axis',
 'apply_over_axes',
 'arange',
 'arccos',
 'arccosh',
 'arcsin',
 'arcsinh',
 'arctan',
 'arctan2',
 'arctanh',
 'argmax',
 'argmin',
 'argpartition',
 'argsort',
 'argwhere',
 'around',
 'array',
 'arr

# create

In [4]:
L = [1,2,3,4,5]
print(L)

[1, 2, 3, 4, 5]


In [5]:
arr = np.array(L)
print(arr)

[1 2 3 4 5]


In [6]:
a2 = np.array([[1,2,3],[4,5,6],[7,8,9]])
a2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
a = np.zeros(5)
a

array([0., 0., 0., 0., 0.])

In [10]:
a3 = np.ones(5)
a3

array([1., 1., 1., 1., 1.])

In [11]:
a4 = np.eye(3)
a4

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [12]:
ar1 = np.zeros((4,3))
ar1

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [13]:
ar2 = np.ones((3,3))
ar2

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [14]:
ar3 = np.arange(10)
ar3

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
ar4 = np.arange(1,11)
ar4

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [16]:
ar5 = np.arange(1,11,2)
ar5

array([1, 3, 5, 7, 9])

In [18]:
ar6 = np.linspace(1,100,10)
ar6

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

In [21]:
ar7 = np.full(10,9)
ar7

array([9, 9, 9, 9, 9, 9, 9, 9, 9, 9])

In [22]:
ar8 = np.full((3,3),9)
ar8

array([[9, 9, 9],
       [9, 9, 9],
       [9, 9, 9]])

In [23]:
r1 = np.random.rand(3,3)
r1

array([[0.79571813, 0.27937006, 0.6265141 ],
       [0.53250616, 0.93388277, 0.96082056],
       [0.1409244 , 0.09845924, 0.34115142]])

In [24]:
r2 = np.random.rand(5)
r2

array([0.25432509, 0.09184257, 0.31338838, 0.37038229, 0.54435851])

In [25]:
r3 = np.random.randint(5)
r3

1

In [26]:
r4 = np.random.randint(1,10)
r4

5

In [27]:
r5 = np.random.randint(1,10,5)
r5

array([9, 5, 1, 5, 5], dtype=int32)

In [29]:
r6 = np.random.randint(1,10,(3,3))
r6

array([[7, 4, 7],
       [4, 7, 5],
       [5, 8, 2]], dtype=int32)

# Indexing of Array

In [3]:
a = np.arange(1,10)

In [4]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
print(a[0])

1


In [6]:
print(a[3])

4


In [7]:
print(a[-1])

9


In [8]:
print(a[-3])

7


In [12]:
a2 = np.random.randint(1,10,(3,3))
a2
# a3 = np.random.randint(1,10,(4,4))
# a3

array([[9, 1, 7],
       [7, 3, 4],
       [4, 8, 7]], dtype=int32)

In [13]:
print(a2[0][1])

1


In [14]:
print(a2[2][0])

4


In [15]:
print(a2[0,1])

1


In [16]:
print(a2[1,2])

4


In [17]:
print(a2)

[[9 1 7]
 [7 3 4]
 [4 8 7]]


# Slicing on array

In [2]:
a = np.arange(3,10)
a

array([3, 4, 5, 6, 7, 8, 9])

In [4]:
a[0:3]

array([3, 4, 5])

In [8]:
a[-1:-5:-1]

array([9, 8, 7, 6])

In [9]:
a[2:6]

array([5, 6, 7, 8])

In [10]:
a

array([3, 4, 5, 6, 7, 8, 9])

In [11]:
a[0::1]

array([3, 4, 5, 6, 7, 8, 9])

In [13]:
a[0::2]

array([3, 5, 7, 9])

In [14]:
a[::]

array([3, 4, 5, 6, 7, 8, 9])

In [15]:
a[::-1]

array([9, 8, 7, 6, 5, 4, 3])

In [16]:
a2 = np.random.randint(1,10,(3,3))
a2

array([[1, 9, 4],
       [1, 3, 8],
       [5, 9, 9]], dtype=int32)

In [19]:
a2[0:2,2]

array([4, 8], dtype=int32)

In [20]:
a2[1,0:2]

array([1, 3], dtype=int32)

In [21]:
a2

array([[1, 9, 4],
       [1, 3, 8],
       [5, 9, 9]], dtype=int32)

In [22]:
a2[:,:]

array([[1, 9, 4],
       [1, 3, 8],
       [5, 9, 9]], dtype=int32)

In [23]:
a2[0:,1:]

array([[9, 4],
       [3, 8],
       [9, 9]], dtype=int32)

# Shape,Size and Datatype of array

In [24]:
a

array([3, 4, 5, 6, 7, 8, 9])

In [25]:
print(a.shape)

(7,)


In [26]:
a2

array([[1, 9, 4],
       [1, 3, 8],
       [5, 9, 9]], dtype=int32)

In [27]:
print(a2.shape)

(3, 3)


In [28]:
print(a2.size)

9


In [29]:
print(a.dtype)

int64


In [30]:
print(a2.dtype)

int32


# Mathematical Operations on Array

In [31]:
a1 = np.arange(11,20)
a2 = np.arange(5,14)

In [33]:
a1

array([11, 12, 13, 14, 15, 16, 17, 18, 19])

In [34]:
a2

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13])

In [35]:
a1 + a2

array([16, 18, 20, 22, 24, 26, 28, 30, 32])

In [36]:
a1 * a2

array([ 55,  72,  91, 112, 135, 160, 187, 216, 247])

In [37]:
a3 = np.array([16,81,25,121,9])
np.sqrt(a3)

array([ 4.,  9.,  5., 11.,  3.])